version: "3.9"
services:
  eureka:
    build: ./eureka-server
    ports: ["8761:8761"]
  gateway:
    build: ./api-gateway
    ports: ["8080:8080"]
    depends_on: [eureka]
  user:
    build: ./user-service
    ports: ["8081:8081"]
    depends_on: [eureka]
  account:
    build: ./account-service
    ports: ["8082:8082"]
    depends_on: [eureka]
  tx:
    build: ./transaction-service
    ports: ["8083:8083"]
    depends_on: [eureka]
